{"name": "test_update_user_by_id", "status": "broken", "statusDetails": {"message": "ValueError: user_id must be a positive integer", "trace": "api_context = <playwright._impl._fetch.APIRequestContext object at 0x000001D58E94CC20>\n\n    @pytest.mark.api\n    def test_update_user_by_id(api_context):\n        users_api = UpdateUsersByIDAPI(api_context)\n        user_id=0\n        update_data = {\n            \"firstName\": \"UpdatedName\",\n            \"lastName\": \"UpdatedLastName\",\n            \"age\": 30\n        }\n>       response = users_api.update_user_by_id(user_id, update_data)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\ntest_users_api.py:164: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api.users_api.UpdateUsersByIDAPI object at 0x000001D58E94D400>, user_id = 0\nuser_data = {'age': 30, 'firstName': 'UpdatedName', 'lastName': 'UpdatedLastName'}\n\n    def update_user_by_id(self, user_id=int, user_data: dict={}):\n        if not isinstance(user_id, int) or user_id <= 0:\n>           raise ValueError(\"user_id must be a positive integer\")\nE           ValueError: user_id must be a positive integer\n\n..\\api\\users_api.py:85: ValueError"}, "start": 1759403101641, "stop": 1759403101641, "uuid": "7d5852a3-313b-4ff2-b2fa-c8be6481609f", "historyId": "2df6582f6d367b9fc13ecc5101259a75", "testCaseId": "2df6582f6d367b9fc13ecc5101259a75", "fullName": "tests.test_users_api#test_update_user_by_id", "labels": [{"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users_api"}, {"name": "host", "value": "PC-2993"}, {"name": "thread", "value": "11240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users_api"}], "titlePath": ["tests", "test_users_api.py"]}