{"name": "test_get_user_profile", "status": "broken", "statusDetails": {"message": "UnboundLocalError: cannot access local variable 'data' where it is not associated with a value", "trace": "api_context = <playwright._impl._fetch.APIRequestContext object at 0x000002131C54C830>\n\n    @pytest.mark.api\n    def test_get_user_profile(api_context):\n        user_profile = AuthAPI(api_context)\n>       token = data[\"accessToken\"]\n                ^^^^\nE       UnboundLocalError: cannot access local variable 'data' where it is not associated with a value\n\ntest_login.py:46: UnboundLocalError"}, "start": 1758625426644, "stop": 1758625426653, "uuid": "4228b4e1-b825-44ed-96be-2e5cafc08b22", "historyId": "cb3dfa0bdd0cd85e7e5b9489b0b964af", "testCaseId": "cb3dfa0bdd0cd85e7e5b9489b0b964af", "fullName": "tests.test_login#test_get_user_profile", "labels": [{"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "PC-2993"}, {"name": "thread", "value": "19236-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}