{"name": "test_get_user_profile", "status": "broken", "statusDetails": {"message": "TypeError: APIClient.post() got an unexpected keyword argument 'data'", "trace": "api_context = <playwright._impl._fetch.APIRequestContext object at 0x000001F299204830>\n\n    @pytest.mark.api\n    def test_get_user_profile(api_context):\n        auth = LoginAPI(api_context)\n>       login_response = auth.login(\n            username=\"emilys\",\n            password=\"emilyspass\",\n            expiresInMins=30\n        )\n\ntest_login.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <api.users_api.LoginAPI object at 0x000001F29916EAD0>, username = 'emilys', password = 'emilyspass', expiresInMins = 30\n\n    def login(self, username: str, password: str, expiresInMins: int = 60):\n        payload = {\n            \"username\": username,\n            \"password\": password,\n            \"expiresInMins\": expiresInMins\n        }\n>       return self.post(self.base_endpoint, data=payload)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       TypeError: APIClient.post() got an unexpected keyword argument 'data'\n\n..\\api\\users_api.py:22: TypeError"}, "start": 1758626834019, "stop": 1758626834019, "uuid": "ec80cc7a-ee32-44ac-a337-9284bf079464", "historyId": "cb3dfa0bdd0cd85e7e5b9489b0b964af", "testCaseId": "cb3dfa0bdd0cd85e7e5b9489b0b964af", "fullName": "tests.test_login#test_get_user_profile", "labels": [{"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "PC-2993"}, {"name": "thread", "value": "20836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}